[package]
name = "testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reverse_string = {path="../reverse-string"}
clock = {path="../clock/"}
unicode-segmentation = "1.11.0"
